"""Composing the two outbound messages the approval gate produces.

Two composers, deliberately not one parameterised by audience:

    compose_review_request  -> internal. The whole ReviewPacket: every rate,
                               every exclusion reason, every runner-up.
    compose_quotation       -> the client. One rate, and nothing about the
                               others (BR-10).

Separate functions because the failure they guard against is sending the wrong
one to the wrong person. A shared template with an `internal: bool` flag makes
that a one-character mistake; two functions that share no body make it a
mis-call the type of the recipient argument does not hide.

Every word here is written deterministically from the record and the selection.
No model composes customer-facing copy — outbound text must be reviewable,
diffable and identical across runs.

Nothing is invented. No tax, surcharge, validity window, insurance, handling
charge, markup or payment term appears, because none is specified anywhere in
this project. What is unavailable says so.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from translog_quote.domain.email import OutboundMessage
from translog_quote.domain.quotation.model import Approved, Quotation, ReviewPacket
from translog_quote.domain.shipment import CargoDimensions, DeliveryType

if TYPE_CHECKING:
    from translog_quote.domain.rates import Selection
    from translog_quote.domain.shipment import ShipmentRecord

#: Marks a message as internal correspondence in its subject line. Two jobs:
#: a person scanning a mailbox can tell a review request from client mail at a
#: glance, and the inbound demo can refuse to ingest its own approval requests
#: as though they were client enquiries.
INTERNAL_SUBJECT_PREFIX = "[TRANSLOG INTERNAL]"

#: Carried on every message built from simulated rates — the internal review
#: and the client quotation alike. The client disclosure is the important one:
#: a demo quotation that reads as a real offer is the expensive mistake this
#: whole flag exists to prevent.
SIMULATED_RATE_NOTICE = (
    "SIMULATED RATE — DEMONSTRATION ONLY. This figure was generated by a demo "
    "rate simulator. No rate provider was contacted and this is not a "
    "commercial offer."
)

_UNAVAILABLE = "Not specified"

_LABELLED_FIELDS: tuple[tuple[str, str], ...] = (
    ("origin", "Origin"),
    ("destination", "Destination"),
    ("commodity", "Commodity"),
    ("cargo_type", "Cargo type"),
    ("is_chemical", "Chemical"),
    ("msds_attached", "MSDS"),
    ("weight_kg", "Gross weight"),
    ("dimensions_in", "Dimensions"),
    ("pcs", "Pieces"),
    ("delivery_type", "Delivery"),
    ("delivery_address", "Delivery address"),
)


def _render(field: str, value: object) -> str:
    if value is None:
        return _UNAVAILABLE
    if field == "weight_kg" and isinstance(value, int | float):
        return f"{value:g} kg"
    if field == "pcs":
        return f"{value} pieces"
    if isinstance(value, CargoDimensions):
        return f"{value.length:g} (L) x {value.width:g} (W) x {value.height:g} (H) inches"
    if isinstance(value, bool):
        return "Yes" if value else "No"
    return str(value)


def _transit(selection: Selection) -> str:
    """ "1 day", not "1 days". This string reaches a client."""
    transit = selection.rate.transit
    if transit is None:  # pragma: no cover - filtering removes unrankable rates
        return _UNAVAILABLE
    unit = transit.unit.value
    return f"{transit.value} {unit.rstrip('s') if transit.value == 1 else unit}"


def _price(selection: Selection) -> str:
    rate = selection.rate
    if rate.total_amount is None or rate.currency is None:  # pragma: no cover - BR-4 filter
        return _UNAVAILABLE
    return f"{rate.total_amount} {rate.currency}"


def _shipment_block(record: ShipmentRecord, *, indent: str = "  ") -> str:
    width = max(len(label) for _, label in _LABELLED_FIELDS) + 2
    return "\n".join(
        f"{indent}{(label + ':').ljust(width)} {_render(field, getattr(record, field))}"
        for field, label in _LABELLED_FIELDS
    )


# --- internal: the review request ----------------------------------------------


def compose_review_subject(packet: ReviewPacket) -> str:
    record = packet.record
    lane = f"{record.origin or '?'} to {record.destination or '?'}"
    return f"{INTERNAL_SUBJECT_PREFIX} Quotation approval required — {packet.request_id} — {lane}"


def compose_review_body(packet: ReviewPacket, *, is_simulated: bool) -> str:
    """Everything the quotation maker needs, including what was excluded.

    Excluded rates are in here deliberately: the maker has to be able to see
    *why* a carrier is absent, and silence there is indistinguishable from a
    bug. This is also exactly why this text must never reach a client — it is
    internal commercial detail.
    """
    selection = packet.selection
    lines: list[str] = [
        "QUOTATION AWAITING APPROVAL",
        "",
        "This quotation has NOT been sent. Nothing will be sent to the client",
        "until a named person explicitly approves it at the Translog terminal.",
        "",
        f"Reference : {packet.request_id}",
        f"Validation: {'VALID' if packet.validation.is_valid else 'INVALID'}",
        f"Clarification sent: {'yes' if packet.clarification_sent else 'no'}",
        "",
        "SHIPMENT",
        "-" * 60,
        _shipment_block(packet.record),
        "",
        "RECOMMENDED RATE",
        "-" * 60,
        f"  Carrier : {selection.rate.carrier_name} ({selection.rate.carrier_code})",
        f"  Service : {selection.rate.product}",
        f"  Transit : {_transit(selection)}",
        f"  Price   : {_price(selection)}",
        f"  Why     : {selection.reason}",
    ]

    if selection.runners_up:
        lines += ["", "ELIGIBLE, NOT CHOSEN", "-" * 60]
        lines += [
            f"  {rate.carrier_code:<4} {rate.carrier_name:<22} {rate.total_amount} {rate.currency}"
            for rate in selection.runners_up
        ]

    if packet.rates.excluded:
        lines += ["", "EXCLUDED, AND WHY", "-" * 60]
        lines += [
            f"  {excluded.rate.carrier_code:<4} {excluded.reason.value:<24} {excluded.detail}"
            for excluded in packet.rates.excluded
        ]

    if is_simulated:
        lines += ["", "-" * 60, SIMULATED_RATE_NOTICE]

    lines += [
        "",
        "-" * 60,
        "TO DECIDE: return to the Translog terminal and enter APPROVE or",
        "DECLINE together with your name. Approving sends the quotation to the",
        "client. Declining sends nothing. There is no automatic approval and no",
        "timeout: if nobody decides, nothing is sent.",
    ]
    return "\n".join(lines)


def compose_review_request(
    packet: ReviewPacket, *, approver_address: str, is_simulated: bool
) -> OutboundMessage:
    """The internal review message. Addressed to the approver, never a client.

    ``approver_address`` is required and has no default. There is no code path
    in which this message is composed without a caller having named where it
    goes.
    """
    return OutboundMessage(
        to_address=approver_address,
        subject=compose_review_subject(packet),
        body_text=compose_review_body(packet, is_simulated=is_simulated),
    )


# --- the client quotation -------------------------------------------------------


def compose_quotation_subject(record: ShipmentRecord, *, reference: str) -> str:
    lane = f"{record.origin or '?'} to {record.destination or '?'}"
    return f"Air freight quotation {reference} — {lane}"


def compose_quotation_body(
    record: ShipmentRecord, selection: Selection, *, reference: str, is_simulated: bool
) -> str:
    """The client-facing quotation. One rate, never a list (BR-10).

    Showing several options would rebuild the manual process this system exists
    to remove — so the runners-up in the review packet do not appear here, and
    neither does any exclusion reason.
    """
    lines: list[str] = [
        "Dear Sir/Madam,",
        "",
        "Thank you for your enquiry. Please find our air freight quotation below.",
        "",
        f"Reference: {reference}",
        "",
        "SHIPMENT",
        "-" * 60,
        _shipment_block(record),
        "",
        "QUOTATION",
        "-" * 60,
    ]
    width = 16
    lines += [
        f"  {'Carrier:'.ljust(width)} {selection.rate.carrier_name} "
        f"({selection.rate.carrier_code})",
        f"  {'Service:'.ljust(width)} {selection.rate.product}",
        f"  {'Delivery scope:'.ljust(width)} {_delivery_scope(record)}",
        f"  {'Transit time:'.ljust(width)} {_transit(selection)}",
        f"  {'Air freight:'.ljust(width)} {_price(selection)}",
        "",
        f"  {'Taxes and surcharges:'} {_UNAVAILABLE}",
        f"  {'Validity:'} {_UNAVAILABLE}",
        f"  {'Payment terms:'} {_UNAVAILABLE}",
    ]

    if is_simulated:
        lines += ["", "-" * 60, SIMULATED_RATE_NOTICE, "-" * 60]

    lines += [
        "",
        "Kind regards,",
        "Translog",
    ]
    return "\n".join(lines)


def _delivery_scope(record: ShipmentRecord) -> str:
    """What the quoted price covers, stated in the quotation itself.

    Spelled out rather than left to the shipment block, because the shipment
    block restates the *request* and this line states the *offer* — the reader
    must not have to infer that the two match. By the time this renders they
    provably do: ``build_quotation`` refuses a rate that cannot perform the
    stated scope.
    """
    if record.delivery_type is DeliveryType.DOOR:
        return "Door delivery included"
    return "Airport to airport"


class IncompatibleService(ValueError):
    """The selected rate cannot perform the delivery scope the client stated.

    A local ``ValueError`` for the same reason ``NotADecision`` is: a domain
    rule states what it will not accept without importing the failure taxonomy
    above it. Eligibility filtering should make this unreachable — this guard
    exists so that if any future path hands the composer an incompatible
    selection, the quotation cannot be built, rather than being built wrong.
    """


def build_quotation(packet: ReviewPacket, approved: Approved, *, is_simulated: bool) -> Quotation:
    """The approved quotation, ready to send.

    ``approved`` is a required positional argument of type ``Approved``. A
    ``Rejected`` decision cannot be passed here, which is the point: there is no
    way to build the thing the sender takes without holding an approval.

    A door-delivery shipment paired with a rate that does not explicitly serve
    door delivery is refused here outright — the last line of defence behind
    the eligibility filter, so a quotation implying a service nobody offered is
    unrepresentable, not merely unlikely.
    """
    if (
        packet.record.delivery_type is DeliveryType.DOOR
        and packet.selection.rate.restrictions.serves_door_delivery is not True
    ):
        raise IncompatibleService(
            f"{packet.request_id}: the selected rate does not declare door delivery, "
            "but the shipment requires it. Refusing to compose a quotation that "
            "implies a service the carrier has not offered."
        )
    return Quotation(
        request_id=packet.request_id,
        record=packet.record,
        selection=packet.selection,
        body_text=compose_quotation_body(
            packet.record,
            packet.selection,
            reference=packet.request_id,
            is_simulated=is_simulated,
        ),
        approved=approved,
    )


def quotation_message(
    quotation: Quotation, *, to_address: str, in_reply_to: str | None
) -> OutboundMessage:
    """The client message carrying an approved quotation.

    Takes a ``Quotation`` — which cannot exist without an ``Approved`` — rather
    than a record and a selection. That is what makes "send an unapproved
    quotation" unrepresentable rather than merely untested.
    """
    return OutboundMessage(
        to_address=to_address,
        subject=compose_quotation_subject(quotation.record, reference=quotation.request_id),
        body_text=quotation.body_text,
        in_reply_to=in_reply_to,
    )
